version: '2'
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
    environment:
    - DEBUG=true
  postgres:
    image: postgres:9.5
    ports:
    - "5432:5432"
    environment:
    - DEBUG=true
  rabbitmq:
    image: rabbitmq:3-management
    hostname: localhost
    ports:
    - "5672:5672"
    - "8081:15672"
    environment:
    - DEBUG=true
