# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('viewers', models.IntegerField()),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveChannel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('OPENED', 'OPENED'), ('CLOSED', 'CLOSED')], default='OPENED', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120, null=True)),
                ('description_html', models.TextField(editable=False)),
                ('resources', models.TextField()),
                ('resources_html', models.TextField(editable=False)),
                ('contributors', models.ManyToManyField(through='live.Contributor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('full_channel', 'Can manage channel'), ('change_channel_close', 'Can permanently close live channel'), ('change_channel_messages', 'Can strike and delete live channel messages'), ('change_channel_contributors', 'Can add, change, delete permissions of other contributors'), ('change_channel_settings', 'Can change title and description of live channel'), ('add_channel_messages', 'Can post channel messages')),
                'verbose_name': 'channel',
                'default_permissions': ('add',),
            },
        ),
        migrations.CreateModel(
            name='LiveMessage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('visible', 'visible'), ('stricken', 'stricken'), ('deleted', 'deleted')], default='visible', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('body_html', models.TextField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live.LiveChannel')),
            ],
            options={
                'verbose_name': 'message',
            },
        ),
        migrations.AddField(
            model_name='contributor',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_set', to='live.LiveChannel'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.LiveChannel'),
        ),
    ]
