# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livechannel',
            options={'default_permissions': ('add',), 'permissions': (('full_permissions', 'Can manage channel'), ('close_livechannel', 'Can permanently close live channel'), ('change_messages', 'Can strike and delete live channel messages'), ('change_contributors', 'Can add, change, delete permissions of other contributors'), ('change_settings', 'Can change title and description of live channel'), ('add_messages', 'Can post channel messages'))},
        ),
    ]
