# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='livechannel',
            options={'default_permissions': ('add',), 'permissions': (('change_channel_close', 'Can permanently close live channel'), ('change_channel_messages', 'Can strike and delete live channel messages'), ('change_channel_contributors', 'Can add, change, delete permissions of other contributors'), ('change_channel_settings', 'Can change title and description of live channel'), ('add_channel_messages', 'Can post channel messages')), 'verbose_name': 'channel'},
        ),
        migrations.RemoveField(
            model_name='livechannel',
            name='contributors',
        ),
        migrations.AddField(
            model_name='livechannel',
            name='contributors_html',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
