# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_auto_20160813_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livechannel',
            name='contributors_html',
        ),
    ]
