# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_auto_20160804_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='livemessage',
            options={'verbose_name': 'message'},
        ),
    ]
