# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_auto_20160731_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='description_html',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
