# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 01:06
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_auto_20160804_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livechannel',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='OPENED', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
