export const CREATE_MESSAGE = 'live.CREATE_MESSAGE';
export const STRIKE_MESSAGE = 'live.STRIKE_MESSAGE';
export const DELETE_MESSAGE = 'live.DELETE_MESSAGE';
export const UPDATE_CHANNEL = 'live.UPDATE_CHANNEL';
export const FETCH_CHANNEL_REQUEST = 'live.FETCH_CHANNEL_REQUEST';
export const FETCH_CHANNEL_FAILURE = 'live.FETCH_CHANNEL_FAILURE';
export const FETCH_CHANNEL_SUCCESS = 'live.FETCH_CHANNEL_SUCCESS';
export const UPDATE_CONNECTION_STATUS = 'live.UPDATE_CONNECTION_STATUS';
